### PR TITLE
feat(deployment) replace static secret with projected volume

### LINKED ISSUE #2731: Use projected token or TokenRequest API
Per https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets spawning Secrets for auto-population is no longer the standard method of obtaining those credentials, and the new methods provide more secure tokens. There are two options for obtaining these:

- A [projected volume](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection), which generates a token in not a Secret and exposes it as a mount similar to the existing mount.
- [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/), which uses a TokenRequest resource whose status will include the token.

We should explore both options and determine which is best for our needs. Some initial thoughts:

- These tokens rotate. Our existing code has nothing to handle this, though it's possible that either client-go or controller-runtime support it natively. We need to confirm behavior after a rotation and build support for it if none exists in libraries.
- Concerns around mesh sidecar support remain. This probably pushes us to the projected volume approach until mesh sidecars are capable of handling their own TokenRequests (IIRC Istio does this, but Kuma and Linkerd do not).

### PR DESCRIPTION
**Pull request by mcharriere**
#### What this PR does / why we need it:
This PR replaces the static service account secret with a projected volume. The projected volume is the standard way to authenticate against the K8s API since v1.21. 
With this change we keep the token mounted only on the ingress controller container and gain the security improvements that the TokenRequests API brings.

#### Which issue this PR fixes
- fixes https://github.com/Kong/kubernetes-ingress-controller/issues/2731

#### Special notes for your reviewer:

- Rotating tokens.

> These tokens rotate. Our existing code has nothing to handle this, though it's possible that either client-go or controller-runtime support it natively. We need to confirm behavior after a rotation and build support for it if none exists in libraries.

client-go introduced support for rotating tokens in https://github.com/kubernetes/kubernetes/pull/67359

- Expiration time

The expiration time has been set to 3607 following the Kubernetes default value. 

#### Checklist
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Review by rainest — COMMENTED** [review]
@mcharriere do you know if this will break backwards-compatibility with older k8s versions (and which?) that don't support projected volumes? This looks fine and is something we should do, we just need to know what older versions would break with projected volumes and whether we need to add any additional templates for older-version compatibility.

**Comment by mcharriere** [comment]
@rainest, yes, you are right. this change breaks on 1.19 and older when `Values.deployment.serviceAccount.automountServiceAccountToken` is enabled (default).

One option is to increase the K8s required version to 1.20 (https://github.com/Kong/charts/blob/main/charts/kong/README.md#prerequisites) and document somewhere that older versions would work disabling `automountServiceAccountToken`.
Alternatively, we could check for the KubeVersion and use the static secret instead. 

WDYT?

**Comment by ubergesundheit** [comment]
helm supports restricting kubernetes versions by specifying field `kubeVersion: ">=1.22.0-0"` in `Chart.yaml`.
 https://helm.sh/docs/topics/charts/#the-kubeversion-field

**Comment by pmalek** [comment]
Hi @ubergesundheit @mcharriere 👋 

> Alternatively, we could check for the KubeVersion and use the static secret instead.

If possible I'd much rather prefer this route at this point to not break our users. What do you think about introducing this capabilities check (via [helm](https://helm.sh/docs/chart_template_guide/builtin_objects/)) in this PR?

BTW: what specific change in k8s is this leveraging that breaks 1.19 and older? I've looked through various docs and couldn't find anything specific that would point to that version.

**Comment by mcharriere** [comment]
> If possible I'd much rather prefer this route at this point to not break our users. What do you think about introducing this capabilities check (via [helm](https://helm.sh/docs/chart_template_guide/builtin_objects/)) in this PR?

Sounds good.

> BTW: what specific change in k8s is this leveraging that breaks 1.19 and older? I've looked through various docs and couldn't find anything specific that would point to that version.

In 1.20, the `RootCAConfigMap` [graduated to beta](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#introducing-rootcaconfigmap), which enabled it by default. Meaning that this configMap mount fails in previous versions: 
```
            - configMap:
                items:
                - key: ca.crt
                  path: ca.crt
                name: kube-root-ca.crt
```
I didn't check if there are alternatives for <1.20, as I think for those cases keeping the current behavior should be fine having in mind that the ingress controller itself doesn't support 1.19 [since v2.6](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#kubernetes).

**Comment by pmalek** [comment]
> In 1.20, the `RootCAConfigMap` [graduated to beta](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#introducing-rootcaconfigmap), which enabled it by default. Meaning that this configMap mount fails in previous versions:
> 
> ```
>             - configMap:
>                 items:
>                 - key: ca.crt
>                   path: ca.crt
>                 name: kube-root-ca.crt
> ```

This was the missing bit. Thanks!

> I didn't check if there are alternatives for <1.20, as I think for those cases keeping the current behavior should be fine having in mind that the ingress controller itself doesn't support 1.19 [since v2.6](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#kubernetes).

We can retain the old behaviour for those versions, no?

**Comment by mcharriere** [comment]
> We can retain the old behaviour for those versions, no?

yes, I just pushed a commit keeping the old behavior for <1.20. I tested it on k8s versions 1.19, 1.20 and 1.25 and it works as expected in all of them.

**Comment by rainest** [comment]
Just added https://github.com/Kong/charts/pull/725 to test across versions, so if ya'll can fetch rebase onto our current main it should confirm the new and legacy behavior.

@pmalek should we indeed need some additional CI values to test this? Although this isn't configured explicitly in any I know of, that shouldn't be an issue since we create the account by default: https://github.com/Kong/charts/blob/892774eb2780794e0cf7522d16a27f3dd621f0a7/charts/kong/values.yaml#L26-L27

**Comment by pmalek** [comment]
> @pmalek should we indeed need some additional CI values to test this? Although this isn't configured explicitly in any I know of, that shouldn't be an issue since we create the account by default:
> 
> https://github.com/Kong/charts/blob/892774eb2780794e0cf7522d16a27f3dd621f0a7/charts/kong/values.yaml#L26-L27

Yes, this should be enough for this PR since we want to test the old and new behaviours for pre 1.20 and 1.20 and up.

**Comment by mcharriere** [comment]
> Just added https://github.com/Kong/charts/pull/725 to test across versions, so if ya'll can fetch rebase onto our current main it should confirm the new and legacy behavior.

@rainest thanks! that's great. the branch is up to date now.

**Review by pmalek — APPROVED** [review]

**Comment by seh** [comment]
Will this change make its way over into the manifests that sit in [the _deploy_ directory of the _Kong/kubernetes-ingress-controller_ repository](https://github.com/Kong/kubernetes-ingress-controller/tree/main/deploy)?

**Comment by rainest** [comment]
@seh there's no reason it shouldn't. https://github.com/Kong/kubernetes-ingress-controller/issues/3475 to track that.

**Pull request merged**
