### PR TITLE
feat(servicemonitor) add relabeling to ServiceMonitor

### PR DESCRIPTION
**Pull request by mcharriere**
#### What this PR does / why we need it:

This PR adds support for ServiceMonitor relabeling option allowing for manipulation of labels before scraping.

#### Special notes for your reviewer:

relabelings is linked to the `RelabelConfigs`, which is applied to samples before scraping. More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

#### Checklist
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Comment by mcharriere** [comment]
I see the tests are failing with unrelated stuff:

```
@@ KIND=Deployment NAME=chartsnap-gateway LINE=758
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: gateway
      app.kubernetes.io/version: "3.6"
-     helm.sh/chart: gateway-2.39.2
+     helm.sh/chart: gateway-2.39.3
    name: chartsnap-gateway
    namespace: default
  spec:
  ```

should I commit all these in this PR or should it go into a separated one?

**Comment by pmalek** [comment]
> I see the tests are failing with unrelated stuff:
> 
> ```
> @@ KIND=Deployment NAME=chartsnap-gateway LINE=758
>       app.kubernetes.io/managed-by: Helm
>       app.kubernetes.io/name: gateway
>       app.kubernetes.io/version: "3.6"
> -     helm.sh/chart: gateway-2.39.2
> +     helm.sh/chart: gateway-2.39.3
>     name: chartsnap-gateway
>     namespace: default
>   spec:
> ```
> 
> should I commit all these in this PR or should it go into a separated one?

Hi 👋 

make sure to rebase on the tip of `main`. The reason you're seeing these is that `main` already includes the [changes that bumped the version to `2.39.3`](https://github.com/Kong/charts/blob/a5ad17a7c4e6fffbe7c79e39eb5b4ca540b28bdc/charts/kong/Chart.yaml#L11).

Or you can alternatively include the required changes yourself by running:

```
make test.golden.update
```

**Comment by mcharriere** [comment]
I'm based on `main`. not sure why those changes were not included in the previous PR.

I added then the test.golden.update changes

**Comment by pmalek** [comment]
The change that you see stems from the fact that use non strict version contraints in our "umbrella" chart `ingress` which uses `kong` as subchart: https://github.com/Kong/charts/blob/2854eb81582004446fc32ca095fde097fcc45cf6/charts/ingress/Chart.yaml#L15

If that constraint was not using `>=` but `==` we'd not see that change as outstanding when `kong` changes its version.

We plan to sort this out.

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
Thanks for the contribution @mcharriere

**Comment by mcharriere** [comment]
awesome! thank you for the review :)

**Pull request merged**
