### PR TITLE
[kong] feat: allow to use replica set and allow to disable proxy service

### PR DESCRIPTION
**Pull request by aldor007**
#### What this PR does / why we need it:

This PR allows deploying kong using the spinnaker 

#### Checklist
- [x] PR is based off the current tip of the `next` branch and targets `next`, not `master`
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

### CODE REVIEW

**Comment by hbagdi** [comment]
Can you explain why do you want to deploy Kong using a ReplicaSet instead of Deployment?

**Comment by aldor007** [comment]
@hbagdi 
Because spinnaker can manage traffic only when using ReplicaSet.  In this mode, spinnaker can deploy new ReplicasaSet using Red/Black strategy  etc. 

Error message from spinnaker: 
> Spinnaker can manage traffic for one ReplicaSet only. Please deploy one ReplicaSet manifest or disable rollout strategies.

**Comment by hbagdi** [comment]
@rainest Thoughts on the ReplicaSet part?

**Comment by rainest** [comment]
Is this the latest version of Spinnaker? The PRs linked from https://github.com/spinnaker/spinnaker/issues/5025 indicate they've at least merged a change that allows multiple.

Does this work if you [add a history limit](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit) to the Deployment template and set it to 0? At least on my own instance the old revisions are the only other RSes associated with the Deployment. If that works, I'd prefer it.

https://www.spinnaker.io/reference/providers/kubernetes/#deploy suggests that Spinnaker should be able to manage Deployments, so I think this is more that it thinks it needs to manage the old versions that aren't doing anything meaningful.

#72 has changes that handle disabling service creation already, so I'd request you remove that part.

**Comment by aldor007** [comment]
Ok, thx.
I will test the new version of spinnaker, so now I'm closing this PR.

**Pull request closed without merging**
