### PR TITLE
feat(kong) add optional prometheus rules

### PR DESCRIPTION
**Pull request by EJKinger**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `next` branch and targets `next`, not `main`
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Comment by andrewgkew** [comment]
@shaneutt - when do you think this will be merged into master? I have a client that is wanting to use this new addition to the chart

**Comment by shaneutt** [comment]
> @shaneutt - when do you think this will be merged into master? I have a client that is wanting to use this new addition to the chart

I put this into review on our project board, so it will be reviewed as soon as possible and if there are no changes needed merged quickly. Given the context you've provided that someone is eagerly anticipating this change I've marked this as a medium severity to indicate that anything with low severity should be prioritized _after_ it.

**Comment by rainest** [comment]
Do we have a reason this would need to go into the chart? It looks like it could be deployed independent of the chart, as the spec doesn't include any templated values and and the rules are mapped to the static metric names, rather than being tied to any specific release.

The configuration here is prescriptive and likely won't be valid for all users. Your application may return many non-2XX statuses in the course of normal operation, or may naturally have very spiky traffic. You may have stricter latency requirements and want alerting at >20ms latency.

Between lack of an obvious link to the specific release and the need for different rules in different environments, I'd recommend we leave this out. It should either be deployed independently without Helm, or if the user in question wants to use Helm to manage it alongside their Kong release, that they create an umbrella chart that includes the Kong chart and resources they want to deploy alongside it in a separate chart.

**Comment by rainest** [comment]
Per conversation elsewhere, the plan here is to open a PR that updates https://docs.konghq.com/gateway/2.7.x/vitals/vitals-prometheus-strategy/ and with a link from https://docs.konghq.com/kubernetes-ingress-controller/2.1.x/guides/prometheus-grafana/, so going ahead and closing the PR here.

**Pull request closed without merging**
