### PR TITLE
fix: fix for comparing semver for enterprise versions

### LINKED ISSUE #856: Chart Image Not Valid Semantic Version
We are using the most recent version of the kong helm chart (2.26) and this morning we are unable to update or install kong on our clusters. 

When we attempt to deploy, we are getting the following error (we have not changed anything with our values file)
image

"error calling semverCompare: Invalid Semantic Version"

### PR DESCRIPTION
**Pull request by pmalek**
#### What this PR does / why we need it:

This fixes an issue where an enterprise version (like e.g. `3.4.0.0`) wouldn't be allowed to be provided.

#### Which issue this PR fixes

Fixes #856 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [ ] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Review by rainest — COMMENTED** [review]
My kingdom for Enterprise using standard semver build tags exclusively for its extra stuff so it at least parses and sticks its mystery values in the designated mystery value box.

What's the intended effect of the change? Regex inscrutability on top of the normal template mess inscrutability will be hard to read in the future, so we should have an explanatory comment inline explaining how this intends to parse input.

We presumably need `^` anchors, correct? What happens if we get a `4.3.4.1` where the tail is a valid semver version we'd compare against?

**Comment by randmonkey** [comment]
What if the `latest` tag is used (as used in KIC nightly integration tests)?

**Comment by pmalek** [comment]
> We presumably need `^` anchors, correct? What happens if we get a `4.3.4.1` where the tail is a valid semver version we'd compare against?

Yes, added that.

I've simplified the change to just extract the first 3 segments if those are detected, otherwise fallback to old behaviour. This will fix the 4 segment versions and leave the old behaviour otherwise.

**Comment by pmalek** [comment]
Not sure why the tests are failing 😠 https://github.com/Kong/charts/actions/runs/5831706278/job/15815656070?pr=857#step:10:2018 the pods deploy successfully 🤔

**Review by rainest — APPROVED** [review]
Problem diagnosis: chart-testing is terrible at reporting issues. `--helm-extra-args "--debug"` will make Helm explain its reasoning, because for some reason it doesn't actually explain them on failure.

Do not use chart-testing's `--debug` in most cases, since it _suppresses_ Helm debug output for some reason.

Deleting the other CI files temporarily makes the output less of a mess.

Problem cause: chart-testing's KIND does not use any LB provider, and Helm will block installs if a spawned LB never gets addresses. All the CI entries need `proxy.type: NodePort`.

**Pull request merged**
