### PR TITLE
[kong] Add serviceMonitor.honorLabels and serviceMonitor.metricRelabelings.

### PR DESCRIPTION
**Pull request by wi1dcard**
#### What this PR does / why we need it:

This PR adds the `serviceMonitor.honorLabels` and `serviceMonitor.metricRelabelings` to values and fixes the TOC in README.md btw.

#### Which issue this PR fixes

None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `next` branch and targets `next`, not `main`
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

### CODE REVIEW

**Comment by rainest** [comment]
Ah, right, merging https://github.com/Kong/charts/pull/395 won't actually fix CI here yet; this is still based on next before that.

@wi1dcard this looks fine, we just need it to pass CI. That broke because of issues with the job configuration, which we've now fixed. If you update your fork with latest next, rebase, and push the result, it should be good to go.

**Comment by wi1dcard** [comment]
> Ah, right, merging #395 won't actually fix CI here yet; this is still based on next before that.
> 
> @wi1dcard this looks fine, we just need it to pass CI. That broke because of issues with the job configuration, which we've now fixed. If you update your fork with latest next, rebase, and push the result, it should be good to go.

Rebased, please check out.

**Review by mflendrich — APPROVED** [review]

**Comment by wi1dcard** [comment]
Hey there, is there any chance we can publish a new release with this PR merged? Thanks!

**Comment by rainest** [comment]
@wi1dcard it got unlucky with timing and the CI issue--it came in as I was about to release 2.2 (which had a bunch of stuff overdue for release due to work elsewhere) and the CI breakage prevented including it (I wish Github had a way to rebase PRs without opening a new branch and cherry-picking from forks).

Does your environment easily allow you to make the changes to the serviceMonitor manually temporarily (although not desirable, Helm 3 will at least preserve the edits if you need to upgrade a release) or work from a local copy of the chart (check out the repo at next and point Helm to the local location instead of using the hosted release)? There are a few things I'd like to get in place before a 2.3 release.

**Comment by wi1dcard** [comment]
> @wi1dcard it got unlucky with timing and the CI issue--it came in as I was about to release 2.2 (which had a bunch of stuff overdue for release due to work elsewhere) and the CI breakage prevented including it (I wish Github had a way to rebase PRs without opening a new branch and cherry-picking from forks).
> 
> Does your environment easily allow you to make the changes to the serviceMonitor manually temporarily (although not desirable, Helm 3 will at least preserve the edits if you need to upgrade a release) or work from a local copy of the chart (check out the repo at next and point Helm to the local location instead of using the hosted release)? There are a few things I'd like to get in place before a 2.3 release.

I see. That makes sense. Thank you for your explanation! I've temporarily made some changes on the ServiceMonitor. I was wondering when will this PR get released so I can apply the changes with Helm. :)

**Pull request merged**
