### PR TITLE
[kong] add hook to init migrations job

### PR DESCRIPTION
**Pull request by rainest**
**What this PR does / why we need it:**

Control the lifecycle of init-migrations jobs with a hook. The job is created after resources are created (namely, after Postgres is created if its subchart is enabled), runs, and is deleted if it succeeds. Install flow should proceed normally after. The job is no longer created during upgrades.

**Which issue this PR fixes**

I thought there was an issue filed for this somewhere, but could not find it. It may have been lost in the depths of the helm/charts repo. See previous discussion in https://github.com/Kong/charts/pull/29#pullrequestreview-351858753

Not deleting the job automatically and creating it for upgrades also allows it to conflict with previous versions of itself, resulting in a very unintuitive error and requiring that users know they need to delete it manually.

### CODE REVIEW

**Comment by rainest** [comment]
Helm 3 creates this job fine, but either Helm 2 does not or something weird is going on with CI. `post-install` should be available there also: https://v2.helm.sh/docs/charts_hooks/#hooks

**Comment by hbagdi** [comment]
`post-install` will not work because Kong deployment doesn't reach healthy status.
We have been bit by it before.

I'd recommend just deleting the migration job on success. We should do it for pre and post upgrade migration jobs as well.

**Comment by rainest** [comment]
It shouldn't unless instructed to. Per that doc:
> 8. Tiller loads the resulting resources into Kubernetes. Note that if the --wait flag is set, Tiller will wait until all resources are in a ready state and will not run the post-install hook until they are ready.

And, in reality, it doesn't: installing with either Helm3 or Helm2 using this change works fine. However, CI does not live in reality, it lives in the world of chart-testing 🙂

chart-testing hard-codes `--wait` into its Helm invocations, e.g. https://github.com/helm/chart-testing/blame/v2.4.0/pkg/tool/helm.go#L62-L63

Not clear why that's the case. It exists in the oldest version in the chart-testing repo, but doesn't in the version that was present in update.sh when it was moved out of the charts repo: https://github.com/helm/charts/pull/5231/files

May be related to timeout handling, but not sure. Sadly, I don't think there's any non-code change way to override it.

**Comment by hbagdi** [comment]
Any reason we really want the `post-install` hook?
(It is so counter-intuitive that it is post-install, it should be pre-install. I know Helm details don't allow for that and that's not the point here either.)

**Comment by rainest** [comment]
`init-migrations` depends on the release spawning Postgres when the subchart is enabled, and Helm waits for `pre-install` resources to become ready (successfully completed for Job resources) before spawning anything else. This will cause `init-migrations` to either get stuck on waiting for Postgres or prevent it from spawning at all (it also depends on the ServiceAccount if using features that need it).

Running in `pre-install` would require that we do the same spawn+delete for the ServiceAccount and Postgres that led to #30. Although that shouldn't be an issue with install, it's still kinda hacky and I'm not actually sure we can do it without forking the Postgres subchart.

`post-install` sounds counter-intuitive, but it does make sense here, in that it's effectively "install Kong and its various dependencies, then run `kong migrations bootstrap` before running `kong start`" given our various initContainers.

**Comment by rainest** [comment]
After some research, I am less keen on K8S' native https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-for-finished-jobs as an alternative. It looks like GKE supports it out of the box without further configuration (or I enabled alpha features earlier on my test cluster and forgot), but EKS and AKS likely do not support it at all:
* At least as of July 2019, EKS [apparently rejects this configuration outright](https://github.com/jaegertracing/jaeger-operator/issues/494). A [request to add it](https://github.com/aws/containers-roadmap/issues/255) remains open, but discussion there indicates it will not be available until it enters beta.
* AKS apparently [ignores it silently and does allow users to enable it via a feature flag](https://github.com/Azure/AKS/issues/833). However, documentation suggests that it's not granular and enables all experimental functionality.

**Comment by hbagdi** [comment]
Two options AFAICS:
1. Contribute a PR to chart-testing.
2. Try using only `helm.sh/hook-delete-policy: "hook-succeeded"` and remove the other annotation and see the behavior of Helm.

**Comment by rainest** [comment]
Not viable as proposed, and would presumably need new Helm functionality (a new hook) to support (it's not possible to fix it in chart-testing only). Closing as such, but keeping the branch around for now.

**Comment by hbagdi** [comment]
Travis,

I thought this was almost there and only CI issues were the blocker. Am I misunderstanding something?

**Comment by rainest** [comment]
The CI issues are quite hard to work around. More detail in https://github.com/helm/chart-testing/issues/202 but in short:
* chart-testing relies on `--wait` to know whether the chart installed successfully. Confirming the same without `--wait` would require some other command that provided the same information.
* Helm has more knowledge of individual release components' status inside `install` execution than outside. It previously had functionality to get that level of detail outside, but that functionality was removed because it was very prone to breaking when other components were updated.

Absent some command-level alternative to `--wait` I can't think of any way to handle this in chart-testing, and the next best option would be a new hook phase we could use in the template. Even assuming that's accepted, it'd break Helm 2 compatibility.

**Pull request closed without merging**
