### PR TITLE
removed appProtocol to fix AKS load balancer

### LINKED ISSUE #694: Kong Proxy Service not reachable from outside with Kubernetes AKS 1.24.6
Hello, 

I'm working on an AKS cluster, with 1.24.6 version.
I installed kong for Kubernetes via the helm chart provided by the doc. 
The chart installs kong correctly and creates the proxy service, on azure I can see the public IP resource has been created and correctly attached to the load balancer.

```
NAME                                 TYPE           CLUSTER-IP   EXTERNAL-IP     PORT(S)                                AGE
service/kong-kong-proxy   LoadBalancer   10.0.59.59   20.23.X.X   80:32127/TCP,443:30452/TCP   10m

NAME                                       ENDPOINTS                             AGE
endpoints/kong-kong-proxy   10.244.38.37:8000,10.244.38.37:8443   10m
```

But when I try to curl the External-IP I get a connection reset.

```
curl: (56) Recv failure: Connection reset by peer
```

I'm not sure what I'm missing since I don't see any particular value on the chart in order to let the proxy work.

Also, I tried to install kong via the bitnami repo charts, and in that, I specify the type of service and the IP.
For that case, I use an azure public IP resource that is in the same resource group (same cluster, same env) as the one created by kong.

Any tips on that behavior?

Thanks.

p.s: if you need any further infos, let me know, this is my first github issue that I open.

### PR DESCRIPTION
**Pull request by objt-ev**
#### What this PR does / why we need it:
It fixes the issue with the loadbalancer in the latest AKS version.

#### Which issue this PR fixes
  - fixes #694 694

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [X] Commits follow the [Kong commit message guidelines]
        branch naming conventions was used, but commit was already done before creating the PR
-(https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Comment by pmalek** [comment]
@rainest This looks fine to me. Do you foresee any problems on platforms other than AKS with this change?

**Comment by rainest** [comment]
I'd [submitted a new feature to the Azure cloud provider](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issue-1398548226) for the vendor-specific behavior here. That [should be available globally now](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issuecomment-1319636090).

@objt-ev can you see if the `service.beta.kubernetes.io/port_<num>_health-probe_protocol` and `service.beta.kubernetes.io/port_<num>_health-probe_port` are now recognized on your deployment, and if adding them to point to another port (admin API on 8444 or status on 8100 should work with either TCP or HTTP checks) on any ports that are failing checks (usually either or both of the proxy and hybrid control listens) to see if that clears it? If it does we can instead add those as default annotations while leaving the (accurate) `appProtocol` default intact.

**Comment by objt-ev** [comment]
> I'd [submitted a new feature to the Azure cloud provider](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issue-1398548226) for the vendor-specific behavior here. That [should be available globally now](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issuecomment-1319636090).
> 
> @objt-ev can you see if the `service.beta.kubernetes.io/port_<num>_health-probe_protocol` and `service.beta.kubernetes.io/port_<num>_health-probe_port` are now recognized on your deployment, and if adding them to point to another port (admin API on 8444 or status on 8100 should work with either TCP or HTTP checks) on any ports that are failing checks (usually either or both of the proxy and hybrid control listens) to see if that clears it? If it does we can instead add those as default annotations while leaving the (accurate) `appProtocol` default intact.

@rainest  globally available ... does this mean in a newer AKS version?

**Comment by pmalek** [comment]
@objt-ev As per [this comment](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issuecomment-1319636090)

> This pr should be cherrypicked to all of release branches and then will be shipped into next cloud provider release(1 week) and it will take another 2 weeks before it is deployed to all of the regions.

I can see it being available in 1.26 and 1.26.1 tags: https://github.com/kubernetes-sigs/cloud-provider-azure/commit/c1092fc4e9f4413b03d51fba188f16a4e5ccf2fb but as for other versions there seem to have been issues cherry picking and it might not have landed in other branches/tags ([#1](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issuecomment-1314625996), [#2](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issuecomment-1314626052), [#3](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2452#issuecomment-1314626116))

**Comment by objt-ev** [comment]
> 

I am running 1.24.6 now... so cannot test directly...

another workaround (instead of removing appProcotol) could be to make the appProtocol configurable via the chart values yaml... default can stay at HTTP, but for 'non-compliant' AKS, we can change it to TCP

**Comment by rainest** [comment]
Are you able to bump to an updated patch release? Not sure if the cherry-pick errors are a red herring, since the Azure contact indicated the changes would still release after those errors appeared--I'd think they'd have mentioned if it weren't actually going to backport because of that.

The release notes indicate that it _did_ go out; https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.24.12 shows it.

**Comment by objt-ev** [comment]
this version bump is not (yet) available in the azure portal

**Review by rainest — CHANGES_REQUESTED** [review]
Alright, given that the timelines to get all the vendor-specific workarounds in place are ambiguous and there isn't solid upstream guidance on what `appProtocol: http` Services should require, reneging on `appProtocol` for the time being. Easier to have `service.beta.kubernetes.io` examples available in values.yaml to override any vendor idiosyncrasies and just not include it in our template.

@objt-ev I'm okay dropping this as proposed in the PR, can you add an item to the CHANGELOG.md to indicate the change? We should be good to merge from there.

**Comment by objt-ev** [comment]
@rainest  changelog updated.

**Review by rainest — APPROVED** [review]

**Comment by braghettos** [comment]
@rainest when do you think this fix will be released?

**Comment by rainest** [comment]
@braghettos hopefully soon, there's another community PR we'd like to get merged in before releasing, to wrap up outstanding new functionality.

**Comment by braghettos** [comment]
@rainest what could be the expected timeline? Is it a matter of days? It's just to understand how to handle this issue in the meanwhile.

**Comment by rainest** [comment]
@braghettos It's out in 2.15.

**Pull request merged**
