### PR TITLE
chore: charts version 2.46 with KIC 3.4

### PR DESCRIPTION
**Pull request by mlavacca**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
xlink release issue https://github.com/Kong/kubernetes-ingress-controller/issues/6844

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [ ] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6844

**Comment by mlavacca** [comment]
> Part of [Kong/kubernetes-ingress-controller#6844](https://github.com/Kong/kubernetes-ingress-controller/issues/6844)

It was already linked in the PR description. An additional reference doesn't harm though :)

**Comment by pmalek** [comment]
Are we going to release `ingress` chart with the bump as well ?

**Comment by mlavacca** [comment]
> Are we going to release `ingress` chart with the bump as well ?

Yep, I'm on it

**Pull request merged**
