### PR TITLE
feat(conf) Adds support startupProbe on Kong Ingress Controller

### PR DESCRIPTION
**Pull request by danibaeyens**
Some big clusters can contain a high number of objects, which might
require more time to be processed during Kong IC boot time.
The new Kubernetes way to protect startup processes is using
`startupProbes`, leaving `livenessProbes` to processes which are
already running and `ready`.

This commit adds support for configuring startupProbe for Kong IC.

#### What this PR does / why we need it:
As it states, Kubernetes provides 3 different probes for controlling containers: liveness, readiness and startup ones. liveness and readiness are common ones, as they are since the beginning of Kubernetes. Startup probes are on beta since 1.18. As in big clusters Kong Ingress Controller can take longer to start, it's safer to have a separate probe for its boot process and keep  the liveness probe without changes. This way, boot can safely take longer and pod can be restarted quicker if needed.

#### Special notes for your reviewer:
As the default value for liveness probe is set to 3 retries (failureThreshold) of 10 seconds each, I've just doubled the number of retries for the startup probe. If it boots faster, it's fine, as the readiness probe will set it as ready before it reaches the 60s threshold (6 retries * 10 seconds).

First contribution to kong project, so I've tried to follow the guide as good as possible

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] PR is based off the current tip of the `next` branch and targets `next`, not `main`
- [X] New or modified sections of values.yaml are documented in the README.md
- [X] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

### CODE REVIEW

**Comment by rainest** [comment]
Interesting. I don't think we should block liveness on reading resources (we should block readiness, but that's fine) initially, though I haven't looked in the code yet to see why that's the case. A controller-side fix is probably a better option here.

Edit: which version are you using? I'm unsure offhand what we did in 1.x, but in 2.x this relies on standard controller-runtime functionality to specify a basic "return success if started at all" function for `/healthz` and start it immediately. The other functions we bind to watch K8S resources should not block that healthz check.

That said, per https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ this is GA as of 1.20. We generally only enable features once they hit GA since our experience with managed providers is that they don't usually have beta features on by default and may not even allow you to enable them.

Since we still maintain support for older versions, this should have a [KubeVersion](https://helm.sh/docs/chart_template_guide/builtin_objects/) gate so that it only populates on versions >= 1.20, and the values comment/README should indicate as much.

**Comment by danibaeyens** [comment]
Just to add some more context, it's related to this discussion: https://github.com/Kong/kubernetes-ingress-controller/discussions/2170

I'll have a look at your comment and modify the PR

**Comment by rainest** [comment]
Ah, gotcha, it's still controller 1.2. Without reviewing the old code in more detail, I'm guessing the liveness handler there is indeed blocked on a successful read of the configuration.

As of 2.x we've replaced a lot of our bespoke generic functionality with [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime), and its liveness handler should just start immediately. Do you still observe the issue if you upgrade/is there any reason you wouldn't be able to use 2.x yet? I'd probably recommend that instead, since ideally we want to avoid additional config surface in the chart unless it's truly necessary.

**Comment by rainest** [comment]
Minor note if 2.x doesn't end up fixing this: we've switched away from using the next branch, and everything goes into main. I've retargeted the PR but you probably still want to rebase on your end.

**Comment by ubergesundheit** [comment]
@rainest is this something you would still accept a PR for?

**Pull request closed without merging**
